# Generated by Django 3.0.2 on 2020-04-25 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200423_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('contestnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Contestant')),
            ],
        ),
    ]
