# Generated by Django 3.0.2 on 2020-04-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
