# Generated by Django 3.0.2 on 2020-04-25 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_vote_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='contestnt',
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='poll.User'),
        ),
    ]
