# Generated by Django 3.0.2 on 2020-04-26 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20200425_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='contestaant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='poll.Contestant'),
        ),
    ]
