# Generated by Django 3.0.2 on 2020-04-26 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_vote_contestaant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote',
        ),
    ]
