# Generated by Django 3.0.2 on 2020-04-28 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20200426_0932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Voter',
        ),
    ]
