# Generated by Django 3.0.2 on 2020-04-28 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20200428_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='voter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poll.Voter'),
        ),
    ]
