# Generated by Django 3.0.2 on 2020-04-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_contestant_voter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='voter',
        ),
    ]
