# Generated by Django 3.0.2 on 2020-04-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_auto_20200428_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
