# Generated by Django 3.0.2 on 2020-04-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_vote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='u_status',
            field=models.IntegerField(default=0),
        ),
    ]
