# Generated by Django 3.0.2 on 2020-04-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_voter_u_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='voter',
        ),
    ]
